import assert from "node:assert/strict";
import test from "node:test";
import { PrismaHistoricalMetricsRepository, PrismaUserRepository, PrismaVideoSynchronizationRepository, PrismaYouTubeAuthorizationRepository, createAnalysisRunPrismaClient, type OwnedAnalysisRunPrismaClient } from "../../persistence/prisma";
import type { HistoricalMetricsRepository } from "../../historical-metrics";
import { YOUTUBE_READONLY_SCOPE } from "../../youtube-authorization";
import { HISTORICAL_CHANNEL, HISTORICAL_USER, historicalInput, runHistoricalRepositoryContract } from "../historical-metrics-repository-conformance.test";
import { deleteOwnedPostgresTestRows, requireTestDatabaseUrl } from "./postgres-test-harness";
const owners = new WeakMap<object, OwnedAnalysisRunPrismaClient>();
async function createRepository(): Promise<PrismaHistoricalMetricsRepository> { const owned = createAnalysisRunPrismaClient(requireTestDatabaseUrl()); await deleteOwnedPostgresTestRows(owned); await new PrismaUserRepository(owned.client).create({ userId: HISTORICAL_USER, email: "historical@example.com", displayName: "Historical", locale: "en", createdAt: "2026-09-01T00:00:00.000Z" }); await new PrismaYouTubeAuthorizationRepository(owned.client).saveAuthorization({ identity: { youtubeIdentityId: "youtube_identity_historical", userId: HISTORICAL_USER, provider: "youtube", providerUserId: "provider_historical", channelId: HISTORICAL_CHANNEL, channelTitle: "Historical Channel", scopes: [YOUTUBE_READONLY_SCOPE], state: "connected", createdAt: "2026-09-01T00:00:00.000Z", updatedAt: "2026-09-01T00:00:00.000Z" }, token: { tokenId: "youtube_token_historical", youtubeIdentityId: "youtube_identity_historical", encryptedRefreshToken: "yt1.test.iv.cipher.tag", encryptionKeyId: "test", createdAt: "2026-09-01T00:00:00.000Z", updatedAt: "2026-09-01T00:00:00.000Z" } }); await owned.client.youTubeChannelRow.create({ data: { channelId: HISTORICAL_CHANNEL, userId: HISTORICAL_USER, youtubeIdentityId: "youtube_identity_historical", title: "Historical Channel", description: "", publishedAt: new Date("2020-01-01T00:00:00.000Z"), viewCount: "100", videoCount: "1", hiddenSubscriberCount: false, keywords: [], brandingSettings: { keywords: [] }, privacyStatus: "public", lastSyncedAt: new Date("2026-09-01T00:00:00.000Z"), syncStatus: "synced", createdAt: new Date("2026-09-01T00:00:00.000Z"), updatedAt: new Date("2026-09-01T00:00:00.000Z") } }); const repository = new PrismaHistoricalMetricsRepository(owned.client); owners.set(repository, owned); return repository; }
async function cleanup(repository: HistoricalMetricsRepository): Promise<void> { const owned = owners.get(repository); if (!owned) return; await deleteOwnedPostgresTestRows(owned); await owned.disconnect(); }
runHistoricalRepositoryContract("Historical metrics repository/PostgreSQL", createRepository, cleanup);
test("historical PostgreSQL tables preserve Decimal precision and contain no secret columns", async () => { const repository = await createRepository(); const owned = owners.get(repository); assert.ok(owned); try { const value = historicalInput("batch_precision", "2026-09-01T00:00:00.000Z", "99999999999999999999"); assert.equal((await repository.persist(value)).status, "success"); const history = await repository.listChannel(HISTORICAL_USER, { limit: 10 }); if (history.status === "success") assert.equal(history.value.items[0]?.observation.viewCount, "99999999999999999999"); const columns = await owned.client.$queryRaw<Array<{ column_name: string }>>`SELECT column_name FROM information_schema.columns WHERE table_schema = 'public' AND table_name IN ('metric_observation_batches','channel_metric_observations','video_metric_observations')`; const names = columns.map((row) => row.column_name.toLowerCase()); for (const forbidden of ["access_token", "refresh_token", "authorization_code", "session_token", "raw_payload", "secret"]) assert.equal(names.includes(forbidden), false); } finally { await cleanup(repository); } });

test("video synchronization atomically creates completed and no-change observations", async () => {
  const historical = await createRepository(); const owned = owners.get(historical); assert.ok(owned);
  try {
    const videos = new PrismaVideoSynchronizationRepository(owned.client);
    const observed = { videoId: "video_sync_observation", channelId: HISTORICAL_CHANNEL, title: "Observed", description: "", publishedAt: "2026-08-01T00:00:00.000Z", durationSeconds: 60, viewCount: "100", likeCount: "2", commentCount: "1", availabilityStatus: "available" as const };
    const current = { ...observed, userId: HISTORICAL_USER, lastSeenAt: "2026-09-01T01:00:00.000Z", lastSyncedAt: "2026-09-01T01:00:00.000Z", createdAt: "2026-09-01T01:00:00.000Z", updatedAt: "2026-09-01T01:00:00.000Z" };
    const sync = { syncId: "sync_observation_completed", userId: HISTORICAL_USER, youtubeIdentityId: "youtube_identity_historical", channelId: HISTORICAL_CHANNEL, outcome: "completed" as const, counts: { discovered: 1, created: 1, updated: 0, unchanged: 0, unavailable: 0 }, coverageCount: 1, coverageLimit: 50, truncated: false, startedAt: "2026-09-01T01:00:00.000Z", completedAt: "2026-09-01T01:00:01.000Z" };
    assert.equal((await videos.complete({ created: [current], updated: [], observed: [observed], synchronization: sync })).status, "success");
    const noChange = { ...sync, syncId: "sync_observation_no_change", outcome: "no-change" as const, counts: { ...sync.counts, created: 0, unchanged: 1 }, startedAt: "2026-09-01T02:00:00.000Z", completedAt: "2026-09-01T02:00:01.000Z" };
    assert.equal((await videos.complete({ created: [], updated: [], observed: [observed], synchronization: noChange })).status, "success");
    const rows = await owned.client.metricObservationBatchRow.findMany({ where: { sourceSyncId: { in: [sync.syncId, noChange.syncId] } }, orderBy: { observedAt: "asc" } });
    assert.deepEqual(rows.map((row) => row.collectionOutcome), ["completed", "no-change"]);
    assert.ok(rows[1] && rows[0] && rows[1].observedAt > rows[0].observedAt);
  } finally { await cleanup(historical); }
});

test("failed synchronization creates audit but no fabricated metric observation", async () => {
  const historical = await createRepository(); const owned = owners.get(historical); assert.ok(owned);
  try { const videos = new PrismaVideoSynchronizationRepository(owned.client); const failed = { syncId: "sync_observation_failed", userId: HISTORICAL_USER, youtubeIdentityId: "youtube_identity_historical", channelId: HISTORICAL_CHANNEL, outcome: "failed" as const, counts: { discovered: 0, created: 0, updated: 0, unchanged: 0, unavailable: 0 }, coverageCount: 0, coverageLimit: 50, truncated: false, failureCode: "api-failure", startedAt: "2026-09-01T03:00:00.000Z", completedAt: "2026-09-01T03:00:01.000Z" }; assert.equal((await videos.recordFailure(failed)).status, "success"); assert.equal(await owned.client.metricObservationBatchRow.count({ where: { sourceSyncId: failed.syncId } }), 0); } finally { await cleanup(historical); }
});

test("observation conflict rolls back current video and synchronization audit", async () => {
  const historical = await createRepository(); const owned = owners.get(historical); assert.ok(owned);
  try { await historical.persist(historicalInput("batch_conflict", "2026-09-01T00:00:00.000Z", "1")); const videos = new PrismaVideoSynchronizationRepository(owned.client); const video = { videoId: "video_rollback_observation", userId: HISTORICAL_USER, channelId: HISTORICAL_CHANNEL, title: "Rollback", description: "", publishedAt: "2026-08-01T00:00:00.000Z", durationSeconds: 60, viewCount: "1", availabilityStatus: "available" as const, lastSeenAt: "2026-09-01T04:00:00.000Z", lastSyncedAt: "2026-09-01T04:00:00.000Z", createdAt: "2026-09-01T04:00:00.000Z", updatedAt: "2026-09-01T04:00:00.000Z" }; const synchronization = { syncId: "sync_batch_conflict", userId: HISTORICAL_USER, youtubeIdentityId: "youtube_identity_historical", channelId: HISTORICAL_CHANNEL, outcome: "completed" as const, counts: { discovered: 1, created: 1, updated: 0, unchanged: 0, unavailable: 0 }, coverageCount: 1, coverageLimit: 50, truncated: false, startedAt: "2026-09-01T04:00:00.000Z", completedAt: "2026-09-01T04:00:01.000Z" }; assert.equal((await videos.complete({ created: [video], updated: [], observed: [video], synchronization })).status, "failure"); assert.equal(await owned.client.youTubeVideoRow.count({ where: { videoId: video.videoId } }), 0); assert.equal(await owned.client.videoSyncRow.count({ where: { syncId: synchronization.syncId } }), 0); } finally { await cleanup(historical); }
});