import assert from "node:assert/strict";
import test from "node:test";
import { InMemoryHistoricalMetricsRepository, type HistoricalMetricsRepository, type MetricObservationBatch } from "../historical-metrics";
export const HISTORICAL_USER = "auth_test_historical_user";
export const HISTORICAL_CHANNEL = "UC_historical_repository";
export const historicalBatch = (id: string, observedAt: string): MetricObservationBatch => ({ batchId: id, userId: HISTORICAL_USER, channelId: HISTORICAL_CHANNEL, sourceSyncId: `sync_${id}`, sourceType: "youtube-video-sync", provider: "youtube", observedAt, collectionOutcome: "completed", availability: "available", coverageCount: 1, coverageLimit: 50, truncated: false, schemaVersion: 1, provenance: "provider-sync", createdAt: observedAt });
export const historicalInput = (id: string, observedAt: string, views: string) => ({ batch: historicalBatch(id, observedAt), channel: { batchId: id, subscriberCount: "10", viewCount: views, videoCount: "1", hiddenSubscriberCount: false, availableFields: ["subscriberCount", "viewCount", "videoCount", "hiddenSubscriberCount"] as const }, videos: [{ batchId: id, videoId: "video_historical", viewCount: views, likeCount: "2", availabilityStatus: "available" as const, availableFields: ["viewCount", "likeCount"] as const }] });
export function runHistoricalRepositoryContract(name: string, factory: () => HistoricalMetricsRepository | Promise<HistoricalMetricsRepository>, cleanup?: (repository: HistoricalMetricsRepository) => Promise<void>): void {
  test(`${name}: persists and reads immutable channel and video observations`, async () => { const repository = await factory(); try { const result = await repository.persist(historicalInput("batch_one", "2026-09-01T00:00:00.000Z", "100")); assert.equal(result.status, "success"); const channel = await repository.listChannel(HISTORICAL_USER, { limit: 10 }); const video = await repository.listVideo(HISTORICAL_USER, "video_historical", { limit: 10 }); assert.equal(channel.status, "success"); assert.equal(video.status, "success"); if (channel.status === "success") assert.equal(channel.value.items[0]?.observation.viewCount, "100"); } finally { await cleanup?.(repository); } });
  test(`${name}: rejects duplicate immutable observations`, async () => { const repository = await factory(); try { const value = historicalInput("batch_duplicate", "2026-09-01T00:00:00.000Z", "100"); assert.equal((await repository.persist(value)).status, "success"); const duplicate = await repository.persist(value); assert.equal(duplicate.status, "failure"); if (duplicate.status === "failure") assert.equal(duplicate.error.code, "duplicate"); } finally { await cleanup?.(repository); } });
  test(`${name}: orders, bounds and paginates history`, async () => { const repository = await factory(); try { await repository.persist(historicalInput("batch_later", "2026-09-02T00:00:00.000Z", "120")); await repository.persist(historicalInput("batch_earlier", "2026-09-01T00:00:00.000Z", "100")); const first = await repository.listChannel(HISTORICAL_USER, { limit: 1 }); assert.equal(first.status, "success"); if (first.status !== "success") return; assert.equal(first.value.items[0]?.batch.batchId, "batch_earlier"); assert.ok(first.value.nextCursor); const second = await repository.listChannel(HISTORICAL_USER, { limit: 1, cursor: first.value.nextCursor }); if (second.status === "success") assert.equal(second.value.items[0]?.batch.batchId, "batch_later"); } finally { await cleanup?.(repository); } });
  test(`${name}: enforces owner isolation for known entity identifiers`, async () => { const repository = await factory(); try { await repository.persist(historicalInput("batch_owner", "2026-09-01T00:00:00.000Z", "100")); const channel = await repository.listChannel("auth_test_foreign_user", { limit: 10 }); const video = await repository.listVideo("auth_test_foreign_user", "video_historical", { limit: 10 }); assert.equal(channel.status === "success" ? channel.value.items.length : -1, 0); assert.equal(video.status, "failure"); } finally { await cleanup?.(repository); } });
}
runHistoricalRepositoryContract("Historical metrics repository/in-memory", () => new InMemoryHistoricalMetricsRepository());
