import assert from "node:assert/strict";
import { test } from "node:test";

import { InMemoryChannelSynchronizationRepository, type ChannelSynchronizationRepository, type YouTubeChannel } from "../index";

export const CHANNEL_SYNC_TIME = "2026-08-03T12:00:00.000Z";
export const channelFixture: YouTubeChannel = { channelId: "UC_repository", userId: "auth_test_channel_user", youtubeIdentityId: "youtube_identity_channel_test", title: "Repository Channel", handle: "@repository", description: "Repository fixture", publishedAt: "2020-01-01T00:00:00.000Z", country: "US", customUrl: "@repository", thumbnailUrl: "https://yt.example/thumb.jpg", bannerUrl: "https://yt.example/banner.jpg", subscriberCount: "100", viewCount: "1000", videoCount: "10", hiddenSubscriberCount: false, defaultLanguage: "en", keywords: ["repository"], brandingSettings: { title: "Repository Channel", keywords: ["repository"] }, privacyStatus: "public", sourceEtag: "etag-repository", lastSyncedAt: CHANNEL_SYNC_TIME, syncStatus: "synced", createdAt: CHANNEL_SYNC_TIME, updatedAt: CHANNEL_SYNC_TIME };
export const synchronizationFixture = { syncId: "youtube_sync_repository", userId: channelFixture.userId, youtubeIdentityId: channelFixture.youtubeIdentityId, channelId: channelFixture.channelId, outcome: "completed" as const, changedFields: ["title"], startedAt: CHANNEL_SYNC_TIME, completedAt: CHANNEL_SYNC_TIME };

export function runChannelSynchronizationRepositoryContract(name: string, factory: () => ChannelSynchronizationRepository | Promise<ChannelSynchronizationRepository>, cleanup?: (repository: ChannelSynchronizationRepository) => Promise<void>): void {
  test(`${name}: atomically persists a channel and completed audit`, async () => { const repository = await factory(); try { const result = await repository.complete({ channel: channelFixture, synchronization: synchronizationFixture }); assert.equal(result.status, "success"); assert.equal((await repository.getByUserId(channelFixture.userId)).status, "success"); assert.equal((await repository.getByChannelId(channelFixture.channelId)).status, "success"); assert.equal((await repository.getLatestByUserId(channelFixture.userId)).status, "success"); } finally { await cleanup?.(repository); } });
  test(`${name}: no-change updates synchronization time without duplicating channel`, async () => { const repository = await factory(); try { await repository.complete({ channel: channelFixture, synchronization: synchronizationFixture }); const result = await repository.recordNoChange({ userId: channelFixture.userId, youtubeIdentityId: channelFixture.youtubeIdentityId, channelId: channelFixture.channelId, syncId: "youtube_sync_no_change", startedAt: "2026-08-03T12:05:00.000Z", completedAt: "2026-08-03T12:05:01.000Z" }); assert.equal(result.status, "success"); const history = await repository.listByUserId(channelFixture.userId, 10); if (history.status === "success") assert.equal(history.value.length, 2); const stored = await repository.getByUserId(channelFixture.userId); if (stored.status === "success") { assert.equal(stored.value.title, channelFixture.title); assert.equal(stored.value.lastSyncedAt, "2026-08-03T12:05:01.000Z"); } } finally { await cleanup?.(repository); } });
  test(`${name}: failed attempts are auditable without fabricating a channel`, async () => { const repository = await factory(); try { const result = await repository.recordFailure({ userId: channelFixture.userId, youtubeIdentityId: channelFixture.youtubeIdentityId, channelId: channelFixture.channelId, syncId: "youtube_sync_failed", failureCode: "quota-exceeded", startedAt: CHANNEL_SYNC_TIME, completedAt: CHANNEL_SYNC_TIME }); assert.equal(result.status, "success"); if (result.status === "success") assert.equal(result.value.failureCode, "quota-exceeded"); assert.equal((await repository.getByUserId(channelFixture.userId)).status, "failure"); } finally { await cleanup?.(repository); } });
}

runChannelSynchronizationRepositoryContract("Channel synchronization repository/in-memory", () => new InMemoryChannelSynchronizationRepository());
