import type { ChannelObservationRecord, HistoricalMetricsRepository, HistoricalPage, HistoricalQuery, HistoricalRepositoryResult, MetricObservationBatch, VideoObservationRecord } from "../../historical-metrics";
import type { AnalysisRunPrismaClient } from "./prisma-client";

const success = <T>(value: T): HistoricalRepositoryResult<T> => ({ status: "success", value });
const failure = <T>(code: "invalid-input" | "not-found" | "duplicate" | "persistence-failure", message: string): HistoricalRepositoryResult<T> => ({ status: "failure", error: { code, message } });
export class PrismaHistoricalMetricsRepository implements HistoricalMetricsRepository {
  constructor(private readonly client: AnalysisRunPrismaClient) {}
  async persist(input: Parameters<HistoricalMetricsRepository["persist"]>[0]): Promise<HistoricalRepositoryResult<MetricObservationBatch>> {
    if (new Set(input.videos.map((video) => video.videoId)).size !== input.videos.length) return failure("duplicate", "Historical observation contains duplicate videos.");
    try { const row = await this.client.metricObservationBatchRow.create({ data: { batchId: input.batch.batchId, userId: input.batch.userId, channelId: input.batch.channelId, sourceSyncId: input.batch.sourceSyncId, sourceType: input.batch.sourceType, provider: input.batch.provider, observedAt: new Date(input.batch.observedAt), collectionOutcome: input.batch.collectionOutcome, availability: input.batch.availability, coverageCount: input.batch.coverageCount, coverageLimit: input.batch.coverageLimit ?? null, truncated: input.batch.truncated, schemaVersion: input.batch.schemaVersion, provenance: input.batch.provenance, createdAt: new Date(input.batch.createdAt), ...(input.channel ? { channelObservation: { create: channelData(input.channel) } } : {}), ...(input.videos.length > 0 ? { videoObservations: { create: input.videos.map(videoData) } } : {}) } }); return success(mapBatch(row)); }
    catch (error) { return prismaCode(error) === "P2002" ? failure("duplicate", "Historical observation already exists.") : failure("persistence-failure", "Historical metric persistence failed."); }
  }
  async listChannel(userId: string, query: HistoricalQuery): Promise<HistoricalRepositoryResult<HistoricalPage<ChannelObservationRecord>>> {
    const valid = validateQuery(query); if (!valid) return failure("invalid-input", "Historical query is invalid.");
    try { const rows = await this.client.metricObservationBatchRow.findMany({ where: { userId: userId.trim(), channelObservation: { isNot: null }, ...dateWhere(query), ...cursorWhere(query) }, include: { channelObservation: true }, orderBy: [{ observedAt: "asc" }, { batchId: "asc" }], take: boundedLimit(query.limit) + 1 }); const limit = boundedLimit(query.limit); const items = rows.slice(0, limit).flatMap((row) => row.channelObservation ? [{ batch: mapBatch(row), observation: { batchId: row.batchId, ...(row.channelObservation.subscriberCount === null ? {} : { subscriberCount: row.channelObservation.subscriberCount.toString() }), ...(row.channelObservation.viewCount === null ? {} : { viewCount: row.channelObservation.viewCount.toString() }), ...(row.channelObservation.videoCount === null ? {} : { videoCount: row.channelObservation.videoCount.toString() }), ...(row.channelObservation.hiddenSubscriberCount === null ? {} : { hiddenSubscriberCount: row.channelObservation.hiddenSubscriberCount }), ...(row.channelObservation.sourceEtag === null ? {} : { sourceEtag: row.channelObservation.sourceEtag }), availableFields: row.channelObservation.availableFields as ChannelObservationRecord["observation"]["availableFields"] } }] : []); const last = items.at(-1); return success({ items, ...(rows.length > limit && last ? { nextCursor: { observedAt: last.batch.observedAt, batchId: last.batch.batchId } } : {}) }); }
    catch { return failure("persistence-failure", "Historical channel metrics could not be loaded."); }
  }
  async listVideo(userId: string, videoId: string, query: HistoricalQuery): Promise<HistoricalRepositoryResult<HistoricalPage<VideoObservationRecord>>> {
    if (!videoId.trim() || !validateQuery(query)) return failure("invalid-input", "Historical query is invalid.");
    try { const rows = await this.client.metricObservationBatchRow.findMany({ where: { userId: userId.trim(), videoObservations: { some: { videoId: videoId.trim() } }, ...dateWhere(query), ...cursorWhere(query) }, include: { videoObservations: { where: { videoId: videoId.trim() } } }, orderBy: [{ observedAt: "asc" }, { batchId: "asc" }], take: boundedLimit(query.limit) + 1 }); if (rows.length === 0) return failure("not-found", "Video history was not found."); const limit = boundedLimit(query.limit); const items = rows.slice(0, limit).flatMap((row) => row.videoObservations.map((video) => ({ batch: mapBatch(row), observation: { batchId: row.batchId, videoId: video.videoId, ...(video.viewCount === null ? {} : { viewCount: video.viewCount.toString() }), ...(video.likeCount === null ? {} : { likeCount: video.likeCount.toString() }), ...(video.commentCount === null ? {} : { commentCount: video.commentCount.toString() }), ...(video.sourceEtag === null ? {} : { sourceEtag: video.sourceEtag }), availabilityStatus: video.availabilityStatus as VideoObservationRecord["observation"]["availabilityStatus"], availableFields: video.availableFields as VideoObservationRecord["observation"]["availableFields"] } }))); const last = items.at(-1); return success({ items, ...(rows.length > limit && last ? { nextCursor: { observedAt: last.batch.observedAt, batchId: last.batch.batchId } } : {}) }); }
    catch { return failure("persistence-failure", "Historical video metrics could not be loaded."); }
  }
  async newest(userId: string): Promise<HistoricalRepositoryResult<MetricObservationBatch>> { try { const row = await this.client.metricObservationBatchRow.findFirst({ where: { userId: userId.trim() }, orderBy: [{ observedAt: "desc" }, { batchId: "asc" }] }); return row ? success(mapBatch(row)) : failure("not-found", "Historical observations were not found."); } catch { return failure("persistence-failure", "Historical metrics could not be loaded."); } }
}
function mapBatch(row: { batchId: string; userId: string; channelId: string; sourceSyncId: string; sourceType: string; provider: string; observedAt: Date; collectionOutcome: string; availability: string; coverageCount: number; coverageLimit: number | null; truncated: boolean; schemaVersion: number; provenance: string; createdAt: Date }): MetricObservationBatch { return { batchId: row.batchId, userId: row.userId, channelId: row.channelId, sourceSyncId: row.sourceSyncId, sourceType: row.sourceType as MetricObservationBatch["sourceType"], provider: "youtube", observedAt: row.observedAt.toISOString(), collectionOutcome: row.collectionOutcome as MetricObservationBatch["collectionOutcome"], availability: row.availability as MetricObservationBatch["availability"], coverageCount: row.coverageCount, ...(row.coverageLimit === null ? {} : { coverageLimit: row.coverageLimit }), truncated: row.truncated, schemaVersion: 1, provenance: row.provenance as MetricObservationBatch["provenance"], createdAt: row.createdAt.toISOString() }; }
function channelData(value: NonNullable<Parameters<HistoricalMetricsRepository["persist"]>[0]["channel"]>) { return { subscriberCount: value.subscriberCount ?? null, viewCount: value.viewCount ?? null, videoCount: value.videoCount ?? null, hiddenSubscriberCount: value.hiddenSubscriberCount ?? null, sourceEtag: value.sourceEtag ?? null, availableFields: [...value.availableFields] }; }
function videoData(value: Parameters<HistoricalMetricsRepository["persist"]>[0]["videos"][number]) { return { videoId: value.videoId, viewCount: value.viewCount ?? null, likeCount: value.likeCount ?? null, commentCount: value.commentCount ?? null, sourceEtag: value.sourceEtag ?? null, availabilityStatus: value.availabilityStatus, availableFields: [...value.availableFields] }; }
function validateQuery(query: HistoricalQuery): boolean { return Number.isInteger(query.limit) && query.limit > 0 && query.limit <= 100 && (!query.from || Number.isFinite(Date.parse(query.from))) && (!query.to || Number.isFinite(Date.parse(query.to))) && (!query.from || !query.to || query.from <= query.to) && (!query.cursor || Number.isFinite(Date.parse(query.cursor.observedAt))); }
function boundedLimit(limit: number): number { return Math.min(Math.max(limit, 1), 100); }
function dateWhere(query: HistoricalQuery) { return query.from || query.to ? { observedAt: { ...(query.from ? { gte: new Date(query.from) } : {}), ...(query.to ? { lte: new Date(query.to) } : {}) } } : {}; }
function cursorWhere(query: HistoricalQuery) { return query.cursor ? { OR: [{ observedAt: { gt: new Date(query.cursor.observedAt) } }, { observedAt: new Date(query.cursor.observedAt), batchId: { gt: query.cursor.batchId } }] } : {}; }
function prismaCode(error: unknown): string | undefined { return typeof error === "object" && error !== null && "code" in error && typeof error.code === "string" ? error.code : undefined; }
