import assert from "node:assert/strict";
import test from "node:test";
import { HistoricalMetricsQueryService, InMemoryHistoricalMetricsRepository, type Clock, type MetricObservationBatch } from "../../../core";
import type { CurrentSessionResolver } from "../../auth";
import { HistoricalMetricsHttpHandlers } from "../historical-metrics-http";
const NOW = "2026-09-03T00:00:00.000Z";
const clock: Clock = { now: () => NOW };
const session = (userId: string | null) => ({ resolveCurrentSession: async () => userId ? { status: "authenticated", principal: { userId, email: `${userId}@example.com`, displayName: userId, locale: "en", status: "active" } } : { status: "unauthenticated" } }) as unknown as CurrentSessionResolver;
const batch = (id: string, userId: string, observedAt: string): MetricObservationBatch => ({ batchId: id, userId, channelId: `channel_${userId}`, sourceSyncId: `sync_${id}`, sourceType: "youtube-video-sync", provider: "youtube", observedAt, collectionOutcome: "completed", availability: "available", coverageCount: 1, coverageLimit: 50, truncated: false, schemaVersion: 1, provenance: "provider-sync", createdAt: observedAt });
async function harness(userId: string | null = "user_a") { const repository = new InMemoryHistoricalMetricsRepository(); for (const [id, observedAt, views] of [["one", "2026-09-01T00:00:00.000Z", "100"], ["two", "2026-09-02T00:00:00.000Z", "120"]] as const) { await repository.persist({ batch: batch(id, "user_a", observedAt), channel: { batchId: id, subscriberCount: "10", viewCount: views, videoCount: "1", hiddenSubscriberCount: false, availableFields: ["subscriberCount", "viewCount", "videoCount", "hiddenSubscriberCount"] }, videos: [{ batchId: id, videoId: "video_a", viewCount: views, availabilityStatus: "available", availableFields: ["viewCount"] }] }); } return new HistoricalMetricsHttpHandlers(session(userId), new HistoricalMetricsQueryService(repository), clock); }
test("historical endpoints require a CreatorOS session and use no-store", async () => { const handlers = await harness(null); const response = await handlers.channelHistory(new Request("http://localhost/api/youtube/metrics/channel/history")); assert.equal(response.status, 401); assert.equal(response.headers.get("cache-control"), "no-store"); });
test("channel history returns chronological safe public records", async () => { const handlers = await harness(); const response = await handlers.channelHistory(new Request("http://localhost/api/youtube/metrics/channel/history?limit=1")); assert.equal(response.status, 200); assert.equal(response.headers.get("cache-control"), "no-store"); const text = await response.text(); assert.equal(text.includes("userId"), false); assert.equal(text.includes("sourceSyncId"), false); assert.equal(text.includes("sourceEtag"), false); const body = JSON.parse(text) as { data: { observations: unknown[]; nextCursor?: string } }; assert.equal(body.data.observations.length, 1); assert.equal(typeof body.data.nextCursor, "string"); });
test("trends expose deterministic deltas and freshness", async () => { const handlers = await harness(); const response = await handlers.trends(new Request("http://localhost/api/youtube/metrics/trends?period=30d")); assert.equal(response.status, 200); const body = await response.json() as { data: { trends: Array<{ metric: string; state: string; absoluteDelta?: string }> } }; const trend = body.data.trends.find((item) => item.metric === "views"); assert.equal(trend?.state, "available"); assert.equal(trend?.absoluteDelta, "20"); });
test("invalid periods and cursors are rejected safely", async () => { const handlers = await harness(); assert.equal((await handlers.trends(new Request("http://localhost/api/youtube/metrics/trends?period=all"))).status, 400); assert.equal((await handlers.channelHistory(new Request("http://localhost/api/youtube/metrics/channel/history?cursor=invalid"))).status, 400); });
test("known foreign video identifiers use safe not-found semantics", async () => { const handlers = await harness("user_b"); const response = await handlers.videoHistory(new Request("http://localhost/api/youtube/metrics/videos/video_a/history"), "video_a"); assert.equal(response.status, 404); const text = await response.text(); assert.equal(text.includes("user_a"), false); });
