import type { Clock, HistoricalMetricsQueryService, HistoricalPeriod, HistoricalQuery } from "../../core";
import type { AuthenticatedPrincipal, CurrentSessionResolver } from "../auth";

export class HistoricalMetricsHttpHandlers {
  constructor(private readonly currentSession: CurrentSessionResolver, private readonly service: HistoricalMetricsQueryService, private readonly clock: Clock) {}
  channelHistory(request: Request): Promise<Response> { return this.withPrincipal(request, async (principal) => { const query = parseQuery(new URL(request.url)); if (!query) return error("INVALID_HISTORY_QUERY", "The historical query is invalid.", 400); const result = await this.service.listChannel(principal.userId, query); return result.status === "success" ? json({ data: { observations: result.value.items.map(publicChannelRecord), ...(result.value.nextCursor ? { nextCursor: encodeCursor(result.value.nextCursor) } : {}) } }) : repositoryError(result.error.code); }); }
  videoHistory(request: Request, videoId: string): Promise<Response> { return this.withPrincipal(request, async (principal) => { const query = parseQuery(new URL(request.url)); if (!query || !videoId.trim()) return error("INVALID_HISTORY_QUERY", "The historical query is invalid.", 400); const result = await this.service.listVideo(principal.userId, videoId, query); return result.status === "success" ? json({ data: { observations: result.value.items.map(publicVideoRecord), ...(result.value.nextCursor ? { nextCursor: encodeCursor(result.value.nextCursor) } : {}) } }) : repositoryError(result.error.code); }); }
  trends(request: Request): Promise<Response> { return this.withPrincipal(request, async (principal) => { const period = new URL(request.url).searchParams.get("period") ?? "30d"; if (!isPeriod(period)) return error("INVALID_TREND_PERIOD", "The trend period is invalid.", 400); const result = await this.service.channelTrends(principal.userId, period, this.clock.now()); return result.status === "success" ? json({ data: result.value }) : repositoryError(result.error.code); }); }
  private async withPrincipal(request: Request, action: (principal: AuthenticatedPrincipal) => Promise<Response>): Promise<Response> { const current = await this.currentSession.resolveCurrentSession(request); return current.status === "authenticated" ? action(current.principal) : error("AUTHENTICATION_REQUIRED", "A valid CreatorOS session is required.", 401); }
}
function parseQuery(url: URL): HistoricalQuery | undefined { const rawLimit = url.searchParams.get("limit") ?? "25"; if (!/^\d+$/u.test(rawLimit)) return undefined; const limit = Number(rawLimit); if (limit < 1 || limit > 100) return undefined; const from = url.searchParams.get("from") ?? undefined; const to = url.searchParams.get("to") ?? undefined; if ((from && !Number.isFinite(Date.parse(from))) || (to && !Number.isFinite(Date.parse(to))) || (from && to && from > to)) return undefined; const rawCursor = url.searchParams.get("cursor"); const cursor = rawCursor ? decodeCursor(rawCursor) : undefined; if (rawCursor && !cursor) return undefined; return { limit, ...(from ? { from } : {}), ...(to ? { to } : {}), ...(cursor ? { cursor } : {}) }; }
function publicBatch(batch: import("../../core").MetricObservationBatch) { return { sourceType: batch.sourceType, provider: batch.provider, observedAt: batch.observedAt, collectionOutcome: batch.collectionOutcome, availability: batch.availability, coverageCount: batch.coverageCount, ...(batch.coverageLimit === undefined ? {} : { coverageLimit: batch.coverageLimit }), truncated: batch.truncated, schemaVersion: batch.schemaVersion, provenance: batch.provenance }; }
function publicChannelRecord(record: import("../../core").ChannelObservationRecord) { const { batchId, sourceEtag, ...metrics } = record.observation; void batchId; void sourceEtag; return { observation: publicBatch(record.batch), metrics }; }
function publicVideoRecord(record: import("../../core").VideoObservationRecord) { const { batchId, sourceEtag, ...metrics } = record.observation; void batchId; void sourceEtag; return { observation: publicBatch(record.batch), metrics }; }
function repositoryError(code: string): Response { return code === "not-found" ? error("HISTORY_NOT_FOUND", "Historical metrics were not found.", 404) : code === "invalid-input" ? error("INVALID_HISTORY_QUERY", "The historical query is invalid.", 400) : error("HISTORY_UNAVAILABLE", "Historical metrics could not be loaded.", 500); }
function isPeriod(value: string): value is HistoricalPeriod { return value === "7d" || value === "30d" || value === "90d"; }
function encodeCursor(cursor: import("../../core").HistoricalCursor): string { return Buffer.from(JSON.stringify(cursor), "utf8").toString("base64url"); }
function decodeCursor(value: string): import("../../core").HistoricalCursor | undefined { try { const parsed: unknown = JSON.parse(Buffer.from(value, "base64url").toString("utf8")); return typeof parsed === "object" && parsed !== null && "observedAt" in parsed && "batchId" in parsed && typeof parsed.observedAt === "string" && typeof parsed.batchId === "string" && Number.isFinite(Date.parse(parsed.observedAt)) && parsed.batchId.length > 0 ? { observedAt: parsed.observedAt, batchId: parsed.batchId } : undefined; } catch { return undefined; } }
function json(body: unknown, status = 200): Response { return Response.json(body, { status, headers: { "cache-control": "no-store" } }); }
function error(code: string, message: string, status: number): Response { return json({ error: { code, message } }, status); }
